### ISSUE TITLE
Is it zero based index or one based index?

### ISSUE THREAD

**Issue by umbalaconmeogia** [avilaton/excel-column-name#5]
It says "Converts zero based index to Excel column name and back", but it converts
A to 1
AA to 27
so I think it is one based index.
Am I wrong?

**Comment by unitof** [comment]
You are correct: it converts a **one**-based index to a alphabetic index. `intToExcelCol(0)` returns an empty string.

Appears there was a merged PR long ago to fix the documentation but the change was never published to npm: 7f9946e

**Comment by avilaton** [comment]
I just published a new version with that.
